[package]
name = "share-faker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clickhouse = "0.11"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
primitive-types = "0.12"
tracing = "0.1"
lazy_static = "1.4"
hex = "0.4"